-- ###########################################
-- # Create
-- ###########################################

-- Create normal entities
    
CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID BIGINT NOT NULL,
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_EXTERNAL_ITEMS (
  ID BIGINT NOT NULL,
  CODE NVARCHAR(255) NOT NULL,
  CODE_NESTED NVARCHAR(255),
  URI NVARCHAR(4000) NOT NULL,
  URN NVARCHAR(4000),
  URN_PROVIDER NVARCHAR(4000),
  MANAGEMENT_APP_URL NVARCHAR(4000),
  VERSION BIGINT NOT NULL,
  TITLE_FK BIGINT,
  TYPE NVARCHAR(255) NOT NULL
);


CREATE TABLE TB_LOCALISED_STRINGS (
  ID BIGINT NOT NULL,
  LABEL NVARCHAR(4000) NOT NULL,
  LOCALE NVARCHAR(255) NOT NULL,
  IS_UNMODIFIABLE BIT,
  VERSION BIGINT NOT NULL,
  INTERNATIONAL_STRING_FK BIGINT NOT NULL
);


CREATE TABLE TB_NOTICES (
  ID BIGINT NOT NULL,
  URN NVARCHAR(255),
  SENDING_APPLICATION NVARCHAR(255) NOT NULL,
  SENDING_USER NVARCHAR(255),
  EXPIRATION_DATE_TZ VARCHAR(50),
  EXPIRATION_DATE DATETIME,
  MARK BIT NOT NULL,
  SUBJECT NVARCHAR(4000) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY NVARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY NVARCHAR(50),
  VERSION BIGINT NOT NULL,
  NOTICE_TYPE NVARCHAR(255) NOT NULL
);


CREATE TABLE TB_APPS (
  ID BIGINT NOT NULL,
  NAME NVARCHAR(255) NOT NULL,
  VERSION BIGINT NOT NULL,
  APP_FK BIGINT NOT NULL
);


CREATE TABLE TB_MESSAGES (
  ID BIGINT NOT NULL,
  TEXT TEXT NOT NULL,
  VERSION BIGINT NOT NULL,
  MESSAGE_FK BIGINT NOT NULL
);


CREATE TABLE TB_RECEIVERS (
  ID BIGINT NOT NULL,
  USERNAME NVARCHAR(255) NOT NULL,
  ACKNOWLEDGE BIT NOT NULL,
  VERSION BIGINT NOT NULL,
  RECEIVER_FK BIGINT NOT NULL
);


CREATE TABLE TB_ROLES (
  ID BIGINT NOT NULL,
  NAME NVARCHAR(255) NOT NULL,
  VERSION BIGINT NOT NULL,
  ROLE_FK BIGINT NOT NULL
);


CREATE TABLE TB_STATISTICAL_OPERATIONS (
  ID BIGINT NOT NULL,
  NAME NVARCHAR(255) NOT NULL,
  VERSION BIGINT NOT NULL,
  STATISTICAL_OPERATION_FK BIGINT NOT NULL
);



-- Create many to many relations
    
CREATE TABLE TB_MESSAGE_RESOURCES (
  RESOURCE_FK BIGINT NOT NULL,
  MESSAGE_FK BIGINT NOT NULL
);



-- Primary keys
    
ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_NOTICES ADD CONSTRAINT PK_TB_NOTICES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_APPS ADD CONSTRAINT PK_TB_APPS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_MESSAGES ADD CONSTRAINT PK_TB_MESSAGES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_RECEIVERS ADD CONSTRAINT PK_TB_RECEIVERS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ROLES ADD CONSTRAINT PK_TB_ROLES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_STATISTICAL_OPERATIONS ADD CONSTRAINT PK_TB_STATISTICAL_OPERATIONS
	PRIMARY KEY (ID)
;

    
ALTER TABLE TB_MESSAGE_RESOURCES ADD CONSTRAINT PK_TB_MESSAGE_RESOURCES
	PRIMARY KEY (RESOURCE_FK, MESSAGE_FK)
;


-- Unique constraints

ALTER TABLE TB_INTERNATIONAL_STRINGS
	ADD CONSTRAINT UQ_TB_INTERNATIONAL_STRINGS UNIQUE (ID)
;


ALTER TABLE TB_EXTERNAL_ITEMS
	ADD CONSTRAINT UQ_TB_EXTERNAL_ITEMS UNIQUE (ID)
;


ALTER TABLE TB_LOCALISED_STRINGS
	ADD CONSTRAINT UQ_TB_LOCALISED_STRINGS UNIQUE (ID)
;


ALTER TABLE TB_NOTICES
	ADD CONSTRAINT UQ_TB_NOTICES UNIQUE (ID)
;


ALTER TABLE TB_APPS
	ADD CONSTRAINT UQ_TB_APPS UNIQUE (ID)
;


ALTER TABLE TB_MESSAGES
	ADD CONSTRAINT UQ_TB_MESSAGES UNIQUE (ID)
;


ALTER TABLE TB_RECEIVERS
	ADD CONSTRAINT UQ_TB_RECEIVERS UNIQUE (ID)
;


ALTER TABLE TB_ROLES
	ADD CONSTRAINT UQ_TB_ROLES UNIQUE (ID)
;


ALTER TABLE TB_STATISTICAL_OPERATIONS
	ADD CONSTRAINT UQ_TB_STATISTICAL_OPERATIONS UNIQUE (ID)
;



-- Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
  
  
ALTER TABLE TB_APPS ADD CONSTRAINT FK_TB_APPS_APP_FK
	FOREIGN KEY (APP_FK) REFERENCES TB_NOTICES (ID)
;

  
ALTER TABLE TB_MESSAGES ADD CONSTRAINT FK_TB_MESSAGES_MESSAGE_FK
	FOREIGN KEY (MESSAGE_FK) REFERENCES TB_NOTICES (ID)
;

  
ALTER TABLE TB_RECEIVERS ADD CONSTRAINT FK_TB_RECEIVERS_RECEIVER_FK
	FOREIGN KEY (RECEIVER_FK) REFERENCES TB_NOTICES (ID)
;

  
ALTER TABLE TB_ROLES ADD CONSTRAINT FK_TB_ROLES_ROLE_FK
	FOREIGN KEY (ROLE_FK) REFERENCES TB_NOTICES (ID)
;

  
ALTER TABLE TB_STATISTICAL_OPERATIONS ADD CONSTRAINT FK_TB_STATISTICAL_OPERATIONS_STATISTICAL_OPERATION_FK
	FOREIGN KEY (STATISTICAL_OPERATION_FK) REFERENCES TB_NOTICES (ID)
;

  

ALTER TABLE TB_MESSAGE_RESOURCES ADD CONSTRAINT FK_TB_MESSAGE_RESOURCES_RESOURCE_FK
	FOREIGN KEY (RESOURCE_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_MESSAGE_RESOURCES ADD CONSTRAINT FK_TB_MESSAGE_RESOURCES_MESSAGE_FK
	FOREIGN KEY (MESSAGE_FK) REFERENCES TB_MESSAGES (ID)
;

  

    


