
    
-- ###########################################
-- # Drop
-- ###########################################
-- Drop index


-- Drop many to many relations
    
DROP TABLE TB_MESSAGE_RESOURCES CASCADE;

-- Drop normal entities
    
DROP TABLE TB_STATISTICAL_OPERATIONS CASCADE;

DROP TABLE TB_ROLES CASCADE;

DROP TABLE TB_RECEIVERS CASCADE;

DROP TABLE TB_MESSAGES CASCADE;

DROP TABLE TB_APPS CASCADE;

DROP TABLE TB_NOTICES CASCADE;

DROP TABLE TB_LOCALISED_STRINGS CASCADE;

DROP TABLE TB_EXTERNAL_ITEMS CASCADE;

DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE;

DROP TABLE TB_SEQUENCES;