

-- ###########################################
-- # Create
-- ###########################################
-- Create pk sequence
    
 	
CREATE sequence SEQ_NOTIFICATIONS;
 	
CREATE sequence SEQ_RECEIVERS;
 	


-- Create normal entities
    
CREATE TABLE TB_NOTIFICATIONS (
  ID NUMBER(19) NOT NULL,
  URN VARCHAR2(255 CHAR),
  SENDING_APPLICATION VARCHAR2(255 CHAR) NOT NULL,
  SENDING_USER VARCHAR2(255 CHAR),
  MAIL VARCHAR2(255 CHAR),
  EXPIRATION_DATE_TZ VARCHAR2(50 CHAR),
  EXPIRATION_DATE TIMESTAMP ,
  REQUIRED_ROLE VARCHAR2(255 CHAR),
  MESSAGE CLOB NOT NULL,
  MARK NUMBER(1,0) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) NOT NULL,
  NOTIFICATION_TYPE VARCHAR2(255 CHAR) NOT NULL,
  NOTIFICATION_CONDITION_TYPE VARCHAR2(255 CHAR)
);


CREATE TABLE TB_RECEIVERS (
  ID NUMBER(19) NOT NULL,
  USERNAME VARCHAR2(255 CHAR) NOT NULL,
  ACKNOWLEDGE NUMBER(1,0) NOT NULL,
  VERSION NUMBER(19) NOT NULL,
  RECEIVER_FK NUMBER(19) NOT NULL
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE TB_NOTIFICATIONS ADD CONSTRAINT PK_TB_NOTIFICATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_RECEIVERS ADD CONSTRAINT PK_TB_RECEIVERS
	PRIMARY KEY (ID)
;

    

-- Unique constraints
    



-- Foreign key constraints
    

  
  
ALTER TABLE TB_RECEIVERS ADD CONSTRAINT FK_TB_RECEIVERS_RECEIVER_FK
	FOREIGN KEY (RECEIVER_FK) REFERENCES TB_NOTIFICATIONS (ID) DEFERRABLE initially IMMEDIATE
;

  

    
    

-- Index


	