// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.siemac.metamac.rest.notifications.v1_0.domain.utils;

import org.siemac.metamac.rest.common.v1_0.domain.Resources;
import org.siemac.metamac.rest.notifications.v1_0.domain.Message;

public class MessageBuilder extends MessageBuilderBase<MessageBuilder> {

    public static MessageBuilder message() {
        return new MessageBuilder();
    }

    public MessageBuilder() {
        super(new Message());
    }

    public Message build() {
        return getInstance();
    }
}

class MessageBuilderBase<GeneratorT extends MessageBuilderBase<GeneratorT>> {

    private Message instance;

    protected MessageBuilderBase(Message aInstance) {
        instance = aInstance;
    }

    protected Message getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withText(String aValue) {
        instance.setText(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withResources(Resources aValue) {
        instance.setResources(aValue);

        return (GeneratorT) this;
    }
}
