// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.siemac.metamac.rest.notifications.v1_0.domain.utils;

import org.siemac.metamac.rest.notifications.v1_0.domain.StatisticalOperation;

public class StatisticalOperationBuilder extends StatisticalOperationBuilderBase<StatisticalOperationBuilder> {

    public static StatisticalOperationBuilder statisticalOperation() {
        return new StatisticalOperationBuilder();
    }

    public StatisticalOperationBuilder() {
        super(new StatisticalOperation());
    }

    public StatisticalOperation build() {
        return getInstance();
    }
}

class StatisticalOperationBuilderBase<GeneratorT extends StatisticalOperationBuilderBase<GeneratorT>> {

    private final StatisticalOperation instance;

    protected StatisticalOperationBuilderBase(StatisticalOperation aInstance) {
        instance = aInstance;
    }

    protected StatisticalOperation getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }
}
