// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.siemac.metamac.notifications.rest.internal.v1_0.domain.utils;

import org.siemac.metamac.rest.notifications.v1_0.domain.Application;

public class ApplicationBuilder extends ApplicationBuilderBase<ApplicationBuilder> {

    public static ApplicationBuilder application() {
        return new ApplicationBuilder();
    }

    public ApplicationBuilder() {
        super(new Application());
    }

    public Application build() {
        return getInstance();
    }
}

class ApplicationBuilderBase<GeneratorT extends ApplicationBuilderBase<GeneratorT>> {

    private Application instance;

    protected ApplicationBuilderBase(Application aInstance) {
        instance = aInstance;
    }

    protected Application getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }
}
