-- ###########################################
-- # Drop
-- ###########################################


-- Disable Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS DROP CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK;

  
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK;

  
  
  
ALTER TABLE TB_APPS DROP CONSTRAINT FK_TB_APPS_APP_FK;

  
ALTER TABLE TB_MESSAGES DROP CONSTRAINT FK_TB_MESSAGES_MESSAGE_FK;

  
ALTER TABLE TB_RECEIVERS DROP CONSTRAINT FK_TB_RECEIVERS_RECEIVER_FK;

  
ALTER TABLE TB_ROLES DROP CONSTRAINT FK_TB_ROLES_ROLE_FK;

  
ALTER TABLE TB_STATISTICAL_OPERATIONS DROP CONSTRAINT FK_TB_STATISTICAL_OPERATIONS_STATISTICAL_OPERATION_FK;

  

ALTER TABLE TB_MESSAGE_RESOURCES DROP CONSTRAINT FK_TB_MESSAGE_RESOURCES_RESOURCE_FK;
ALTER TABLE TB_MESSAGE_RESOURCES DROP CONSTRAINT FK_TB_MESSAGE_RESOURCES_MESSAGE_FK;

  

    
-- Drop many to many relations
    
DROP TABLE TB_MESSAGE_RESOURCES;

-- Drop normal entities
    
DROP TABLE TB_STATISTICAL_OPERATIONS;

DROP TABLE TB_ROLES;

DROP TABLE TB_RECEIVERS;

DROP TABLE TB_MESSAGES;

DROP TABLE TB_APPS;

DROP TABLE TB_NOTICES;

DROP TABLE TB_LOCALISED_STRINGS;

DROP TABLE TB_EXTERNAL_ITEMS;

DROP TABLE TB_INTERNATIONAL_STRINGS;
