
    
-- ###########################################
-- # Drop
-- ###########################################
-- Drop index


-- Drop many to many relations
    
DROP TABLE TB_MESSAGE_RESOURCES CASCADE CONSTRAINTS PURGE;

-- Drop normal entities
    
DROP TABLE TB_STATISTICAL_OPERATIONS CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_ROLES CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_RECEIVERS CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_MESSAGES CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_APPS CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_NOTICES CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_LOCALISED_STRINGS CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_EXTERNAL_ITEMS CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_INTERNATIONAL_STRINGS CASCADE CONSTRAINTS PURGE;


-- Drop pk sequence
     


	